# -*- coding: utf-8 -*-
"""mental_health_pln (BERT).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cWRNjhVwnw9xYyF-hY8VtT-xBLvLfOj

# Bibliotecas

## Instalaciones
"""

!pip install -U spacy #-U para asegurar que se utiliza la biblioteca mas reciente, de update
!pip install -U gensim
!pip install wordcloud
!python -m spacy download en_core_web_lg

"""## Importaciones"""

#se reutilizan las bibliotecas de la practica de embeddings
import spacy
import gensim.downloader
import nltk
from nltk.corpus import stopwords
import re
import numpy as np
import pandas as pd
import joblib #para guardar los modelos, porque tardan mucho en entrenarse y ya baje n_iter a 10
#Bibliotecas para los modelos
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold, train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from lightgbm import LGBMClassifier
#EDA
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.probability import FreqDist
from wordcloud import WordCloud
import os

#import warnings
#warnings.filterwarnings('ignore')
nltk.download('stopwords')
def separador():
    print("\n" + "=" * 170 + "\n")
def header(Titulo):
  por=((170-len(Titulo))//10)
  a=int(1.2*por)
  print("."*a+"·"*a+"~"*a+"≈"*a+"≋"
  *int(por*.2),Titulo,"≋"*int(por*.2)
  +"≈"*a+"~"*a+"·"*a+"."*a,"\n\n")

"""# Spacy y función para limpiar y lematizar"""

nlp = spacy.load("en_core_web_lg")
stop_words_en = set(stopwords.words('english'))
print('Carga de spaCy y stopwords exitosa')

def limpiar_y_lematizar(texto):
    doc = nlp(texto.lower())
    lemmas = [token.lemma_ for token in doc
              if not token.is_stop and
                 token.lemma_ not in stop_words_en and
                 token.is_alpha and
                 len(token.lemma_) > 1]
    return lemmas

print('Función de limpieza definida')

"""# CHECKPOINT DE **VECTORIZACION**"""

# ====================================================================
# CELDA DE PREPARACIÓN DE DATOS (Con Checkpoint "Inteligente")
# ====================================================================
 # Asegúrate de que esto esté en tu celda de importaciones

# --- 1. Definir la ruta del Checkpoint ---
ruta_checkpoint = "/content/drive/MyDrive/PDS/mental_health_pln/mental_health_LIMPIO.pkl"
ruta_original_csv = "/content/drive/MyDrive/PDS/mental_health_pln/mental_health.csv"

# --- 2. La Lógica "Inteligente" ---
if os.path.exists(ruta_checkpoint):
    # ==========================================================
    # FASE 2: EL ARCHIVO SÍ EXISTE (Rápido)
    # ==========================================================
    print(f"¡Checkpoint encontrado! Cargando datos limpios desde {ruta_checkpoint}...")
    df = pd.read_pickle(ruta_checkpoint)
    print("Datos limpios cargados exitosamente.")

    # Cargar solo el modelo GENSIM (para vectorizar)
    model_gensim = gensim.downloader.load('fasttext-wiki-news-subwords-300')
    VECTOR_SIZE = model_gensim.vector_size
    print("Modelo Gensim cargado.")

else:
    # ==========================================================
    # FASE 1: EL ARCHIVO NO EXISTE (Lento - Correr 1 vez)
    # ==========================================================
    print(f"Checkpoint no encontrado. Ejecutando la limpieza (tardará ~50 min)...")

    # Cargar el modelo SPACY (para limpiar)
    nlp = spacy.load("en_core_web_lg")
    stop_words_en = set(stopwords.words('english'))
    print("Modelo spaCy cargado.")

    # Cargar el CSV original
    df = pd.read_csv(ruta_original_csv)

    # Limpieza de columnas (tu código)
    df.drop(columns=['Unnamed: 0'], inplace=True)
    df.rename(columns={'statement': 'phrase', 'status': 'prompt'}, inplace=True)
    df['phrase'] = df['phrase'].astype(str)
    df['prompt'] = df['prompt'].astype(str)
    df = df.dropna(subset=['phrase'])
    print("CSV original cargado y limpiado.")

    # --- El paso de 50 minutos ---
    print("Iniciando limpieza de spaCy...")
    df['lemas_limpios'] = df['phrase'].apply(limpiar_y_lematizar)
    print("Limpieza completada.")

    # --- Guardar el checkpoint para la próxima vez ---
    df.to_pickle(ruta_checkpoint)
    print(f"¡CHECKPOINT CREADO! Datos limpios guardados en: {ruta_checkpoint}")

    # Cargar el modelo GENSIM (necesario para el siguiente paso)
    model_gensim = gensim.downloader.load('fasttext-wiki-news-subwords-300')
    VECTOR_SIZE = model_gensim.vector_size
    print("Modelo Gensim cargado.")

# ====================================================================
# AHORA, LA VECTORIZACIÓN (RÁPIDA)
# ====================================================================

# (Asegúrate de haber definido esta función en una celda anterior)
def vectorizar_lemas(lemas_limpios, modelo):
    vectores_palabras = [modelo[palabra] for palabra in lemas_limpios
                         if palabra in modelo.key_to_index]
    if len(vectores_palabras) > 0:
        return np.mean(vectores_palabras, axis=0)
    else:
        return np.zeros(VECTOR_SIZE)

# Vectorización (¡Ahora usa la columna 'lemas_limpios' que SIEMPRE existe!)
print("Vectorizando lemas (esto será rápido)...")
df['vector'] = df['lemas_limpios'].apply(lambda lemas: vectorizar_lemas(lemas, model_gensim))

# --- Creación de X e y (como lo tenías) ---
X = np.array(df['vector'].tolist())
le = LabelEncoder()
y = le.fit_transform(df['prompt'])

print(f"Forma de X (vectores): {X.shape}")
print(f"Forma de y (etiquetas): {X.shape}")
print("¡Preparación de datos lista! Puedes ir al modelado.")

"""# EDA

## Gráficas
"""

print(df.info())
separador()
print(f"\nNúmero de clases únicas: {df['prompt'].nunique()}")
separador()
plt.figure(figsize=(10, 8))
sns.countplot(y='prompt', data=df, palette='mako', order=df['prompt'].value_counts().index)
plt.title('Distribución de Síntomas (Clases)')
plt.xlabel('Frecuencia')
plt.ylabel('Síntoma')
plt.tight_layout()
plt.show()


#Frecuencia y wordcloud

print("Procesando texto para EDA (esto puede tardar en un dataset grande)...")


#Esto crea una Serie de Pandas donde cada celda es una [lista, de, lemas]
listas_de_lemas = df['phrase'].apply(limpiar_y_lematizar)

print("Limpieza completada. Agregando lemas...")

#Ahora, une todas esas listas pequeñas en una lista gigante de todos los lemas
# .sum() en una Serie de listas las concatena.
todos_los_lemas = listas_de_lemas.sum()

fdist = nltk.FreqDist(todos_los_lemas)
print(f"\n25 Palabras más frecuentes:\n{fdist.most_common(25)}")

plt.figure(figsize=(12, 6))
fdist.plot(25, cumulative=False, title='Top 25 de Palabras más Frecuentes')
plt.show()

# 4. Une la lista gigante de lemas en un string para el WordCloud
texto_para_wordcloud = " ".join(todos_los_lemas)
wordcloud = WordCloud(width=950, height=600, background_color='white',
                      collocations=False).generate(texto_para_wordcloud)

# Muestra la nube de palabras original
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title('Nube de Palabras')
plt.show()

"""# Pipelines

## LIGHTGBM
"""

# ====================================================================
# PASO 6 MODIFICADO (SOLO LightGBM)
# ====================================================================

# Vectorización del texto (¡AHORA ES RÁPIDO!) y definicion de X, y
print("Vectorizando (esto será rápido ahora)...")
df['vector'] = df['lemas_limpios'].apply(lambda lemas: vectorizar_lemas(lemas, model_gensim))
X = np.array(df['vector'].tolist())
le = LabelEncoder()
y = le.fit_transform(df['prompt'])

print(f"Forma de X (vectores): {X.shape}")
print(f"Forma de y (etiquetas): {y.shape}")

rs=11 #para que todos los random_State sean iguales, y los resultados replicables

# Hold out de 80% para entrenamiento con validación cruzada de 10 folds y 20% para el test al final
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20,random_state=rs,stratify=y)

cv_strat_10 = StratifiedKFold(n_splits=10, shuffle=True, random_state=rs)


pipe_lgbm = Pipeline([('model', LGBMClassifier(random_state=rs, n_jobs=-1, class_weight='balanced'))])

# Parámetros para optimizar LGBM
params_lgbm = {
    'model__n_estimators': [100, 200, 400],
    'model__learning_rate': [0.01, 0.05, 0.1],
    'model__num_leaves': [31, 50, 70]}

n_iter_search = 10 #Para que no dure TANTO
scoring_metric = 'f1_weighted'

# Define SOLO el RandomizedSearch para LightGBM
rs_lgbm = RandomizedSearchCV(pipe_lgbm, params_lgbm, n_iter=n_iter_search, cv=cv_strat_10, scoring=scoring_metric, random_state=rs, verbose=1)

# Define la lista de 'searches' solo con LGBM
searches = [('LightGBM', rs_lgbm)]

print("Configuración de LightGBM (único modelo) lista.")

"""# Entrenamiento"""

header('Entrenamiento de modelos')
results_list = []
DRIVE_PATH = "/content/drive/MyDrive/MAESTRIA/PLN/"
# ------------------------------------------------

for nombre_modelo, search_obj in searches:
    print(f"\nEntrenando {nombre_modelo}...")
    search_obj.fit(X_train, y_train)
    print(f"Entrenamiento de {nombre_modelo} completado.")

    # --- CORRECCIÓN AQUÍ ---
    # Se quita 'lightgbm' del nombre para evitar duplicados
    model_filename = f'modelo_entrenado_mental_health_{nombre_modelo.replace(" ", "_")}.joblib'
    # -----------------------

    full_save_path = DRIVE_PATH + model_filename
    joblib.dump(search_obj, full_save_path)
    print(f"Modelo guardado en: {full_save_path}")

    #Se suman los resultados a la lista "results_list"
    results_list.append({'Modelo': nombre_modelo,'Best Score (CV F1-Weighted)': search_obj.best_score_,'Best Params': search_obj.best_params_})

"""# Mejor Modelo"""

header('Comparación de resultados')

# 1. Convierte a DF e imprime la tabla (esto sigue siendo útil para ver los params)
results_df = pd.DataFrame(results_list)
print(results_df.to_string())

# 2. Simplificación: Ya no necesitas buscar el "mejor" modelo.
# Sabemos que 'searches' solo tiene un item.
mejor_modelo_nombre = searches[0][0]  # Será 'LightGBM'
mejor_search_obj = searches[0][1]     # Será 'rs_lgbm'

# El resto de tu código es perfecto
print(f"\n--- REPORTE FINAL DEL MEJOR MODELO ({mejor_modelo_nombre}) EN DATOS DE PRUEBA (TEST) ---")

y_pred_final = mejor_search_obj.predict(X_test)
print(classification_report(y_test, y_pred_final, target_names=le.classes_))
acc_final = accuracy_score(y_test, y_pred_final)
print(f"Accuracy final en Test: {acc_final:.4f}")

"""# ================================================================================================================

# RED NEURONAL BERT

# INSTALACIONES
"""

#Hugging face
#!pip install -U transformers datasets accelerate scikit-learn
#!pip install -U pandas numpy
!pip install evaluate

"""# IMPORTACIONES Y CARGA DE DATOS"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from datasets import Dataset, DatasetDict
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate
import os
#CSV ORIGINAL
df = pd.read_csv("/content/drive/MyDrive/PDS/mental_health_pln/mental_health.csv")

#Se elimina la primera columna porque no aporta nada
df.drop(columns=['Unnamed: 0'], inplace=True)
df.rename(columns={'statement': 'text', 'status': 'label'}, inplace=True)
df = df.dropna(subset=['text'])

#se convierten etiquetas a numeros
le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

# Guardamos el mapa para saber qué es qué después
label_map = {index: label for index, label in enumerate(le.classes_)}
print(f"Clases detectadas: {label_map}")

#Divisón de datos
train_df, test_df = train_test_split(df, test_size=0.2, stratify=df['label'], random_state=42)

# 5. Convertir a formato Hugging Face Dataset
# Esto hace que el manejo de datos sea mucho más eficiente para la GPU
dataset = DatasetDict({"train": Dataset.from_pandas(train_df),"test": Dataset.from_pandas(test_df)})

print("\nDatos listos para BERT.")
print(dataset)

"""# Tokenización"""

from transformers import AutoTokenizer

# Usamos 'bert-base-cased' (Cased es mejor si las mayúsculas importan, o 'uncased' si no)
# Para salud mental, a veces MAYÚSCULAS significan gritos/estrés, así que probemos 'cased'.
model_checkpoint = "bert-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def preprocess_function(examples):
    # Truncation=True corta frases muy largas (límite de BERT es 512 tokens)
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

print("Tokenizando datos (esto es rápido)...")
tokenized_datasets = dataset.map(preprocess_function, batched=True)
print("Tokenización completada.")

"""# Configuración del modelo y entrenamiento"""

os.environ["WANDB_DISABLED"] = "true"
model_checkpoint = "bert-base-cased"
# TU RUTA ORIGINAL
model_save_path = "/content/drive/MyDrive/MAESTRIA/PLN/bert_final_model"

# --- 2. Lógica de Decisión: ¿Cargar o Entrenar? ---
if os.path.exists(model_save_path):
    print(f"✅ Modelo encontrado en: {model_save_path}")


    # Cargar desde TU carpeta
    model = AutoModelForSequenceClassification.from_pretrained(model_save_path)
    se_requiere_entrenamiento = False

else:
    print(f"❌ No se encontró modelo en: {model_save_path}")
    model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=7)
    se_requiere_entrenamiento = True

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

training_args = TrainingArguments(
    output_dir="./bert_temp_checkpoints",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    seed=11,
    data_seed=11)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics)

# --- 4. Ejecución del Entrenamiento (Solo si es necesario) ---
if se_requiere_entrenamiento:
    print("\n🚀 Comienzo del entrenamiento...")
    trainer.train()

    print(f"\n💾 Guardando modelo final y tokenizer en: {model_save_path}")
    trainer.save_model(model_save_path)
    tokenizer.save_pretrained(model_save_path) # Importante guardar el tokenizer también
else:
    print("\n⏭️ Entrenamiento omitido. Pasando directo a evaluación.")

"""# Evaluación final"""

header("Evaluación del modelo final")

predictions = trainer.predict(tokenized_datasets["test"])
preds = np.argmax(predictions.predictions, axis=-1)
true_labels = predictions.label_ids

#Classification report
print("\nReporte de clasificación con BERT")
# Usamos le.classes_ para poner los nombres reales (Anxiety, Depression, etc.)
print(classification_report(true_labels, preds, target_names=le.classes_))

#Matríz de confusión
cm = confusion_matrix(true_labels, preds)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=le.classes_, yticklabels=le.classes_)
plt.ylabel('Verdadero')
plt.xlabel('Predicho')
plt.title('Matriz de Confusión - BERT')
plt.show()

#Se guarda el modelo final
model_save_path = "/content/drive/MyDrive/MAESTRIA/PLN/bert_final_model"
trainer.save_model(model_save_path)
print(f"Modelo guardado en: {model_save_path}")